#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

# Light-weight ORAN SMO
services:

  sdnc-web:
    image: ${SDNC_WEB_IMAGE}
    container_name: sdnc-web
    environment:
      - ENABLE_OAUTH=false
      - SDNRHOST=sdnr
    ports:
      - 8080:8080
    depends_on:
      - sdnr
    healthcheck:
      test: "curl --silent --fail http://localhost:8080/ready > /dev/null || exit 1"
      interval: 10s
      timeout: 10s
      retries: 45
    volumes:
      - ./third_party_elements/smo/sdnc-web/odlux.application.list:/app/odlux.application.list
    networks:
      smo:
        ipv4_address: 172.21.0.100

  sdnr:
    image: ${SDNC_IMAGE}
    container_name: sdnr
    environment:
      - SDNRCONTROLLERID=c94bbd5f-d456-44bd-aa7a-47b274f73762
      - A1_ADAPTER_NORTHBOUND=false
      - CCSDK_REPLICAS=0
      - DOMAIN=""
      - ENABLE_OAUTH=false
      - ODL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ODL_CERT_DIR=/opt/opendaylight/current/certs
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
      - SDNRDBURL=http://sdnrdb:9200
      - SDNRDBTYPE=ELASTICSEARCH
      - SDNRDM=false
      - SDNRINIT=true
      - SDNRONLY=true
      - SDNRWT=true
      - SDNR_ASYNC_HANDLING=true
      - SDNR_ASYNC_POOLSIZE=200
      - SDNR_NETCONF_CALLHOME_ENABLED=true
      - JAVA_OPTS=-Xms256m -Xmx4g
    volumes:
      - ./third_party_elements/smo/sdnc/devicemanager.properties:/opt/opendaylight/etc/devicemanager.properties
      - ./third_party_elements/smo/sdnc/mountpoint-registrar.properties:/opt/opendaylight/etc/mountpoint-registrar.properties
    depends_on:
      - sdnrdb
    networks:
      - smo

  sdnrdb:
    image: ${SDNRDB_IMAGE}
    container_name: sdnrdb
    environment:
      - discovery.type=single-node
    networks:
      - smo

  dcae-ves-collector:
    #    image: ${DCAE_VES_COLLECTOR_IMAGE}
    image: ${VES_COLLECTOR_IMAGE}-modified
    build:
      context: ./third_party_elements/smo/dcae/ves-image
      args:
        - BASEIMAGE=${VES_COLLECTOR_IMAGE}
    container_name: ves-collector
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    hostname: ves-collector
    networks:
      - smo
    ports:
      # - 8080:8080
      - 8443:8443
    volumes:
      - ./third_party_elements/smo/dcae/collector.properties:/opt/app/VESCollector/etc/collector.properties
      - ./third_party_elements/smo/dcae/ves-dmaap-config.json:/opt/app/VESCollector/etc/ves-dmaap-config.json
  #    - ./dcae/externalRepo:/opt/app/VESCollector/etc/externalRepo

  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    container_name: zookeeper
    command: [ "sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties" ]
    # ports:
    #  - 2181:2181
    environment:
      LOG_DIR: /tmp/logs
      ZOOKEEPER_REPLICAS: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_MAX_CLIENT_CNXNS: 200
      ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: 3
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: 24
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/jaas/zk_server_jaas.conf -Dzookeeper.kerberos.removeHostFromPrincipal=true -Dzookeeper.kerberos.removeRealmFromPrincipal=true -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -Dzookeeper.requireClientAuthScheme=sasl
    volumes:
      - ./third_party_elements/smo/dmaap/zk_server_jaas.conf:/etc/zookeeper/secrets/jaas/zk_server_jaas.conf
      # ports:
      # - 2181:2181
    networks:
      - smo

  kafka:
    container_name: kafka
    image: ${KAFKA_IMAGE}
    hostname: kafka
    depends_on:
      - zookeeper
    command: [ "sh", "-c", "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}" ]
    environment:
      LOG_DIR: "/tmp/logs"
      enableCadi: 'false'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 40000
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 40000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_PLAINTEXT
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/jaas/zk_client_jaas.conf
      KAFKA_ZOOKEEPER_SET_ACL: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      # Reduced the number of partitions only to avoid the timeout error for the first subscribe call in slow environment
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 2
    volumes:
      - ./third_party_elements/smo/dmaap/zk_client_jaas.conf:/etc/kafka/secrets/jaas/zk_client_jaas.conf
    networks:
      - smo
    # ports:
    # - 9092:9092

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8085:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - smo

networks:
  smo:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
