# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

services:
  dhcp_server:
    image: ocudu/dhcp-server:latest
    build:
      context: ocudu_elements/ocudu_dhcp/server
      dockerfile: Dockerfile
    entrypoint: ["entrypoint.sh"]
    container_name: ocudu-dhcp-server-isc-kea
    restart: unless-stopped
    network_mode: host
    volumes:
      - kea4-var:/var/lib/kea

volumes:
  kea4-var: