#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

services:

  netconf:
    image: ocudu/netconf:latest
    build:
      context: ocudu_elements/ocudu_netconf
      dockerfile: Dockerfile
    entrypoint: ["entrypoint.sh", "/config/default_config.xml"]
    container_name: ocudu-netconf
    ports:
      # Comment to hide netconf port from outside of the docker network
      - 830:830
    volumes:
      - ${NETCONF_DEFAULT_CFG:-${PWD}/ocudu_elements/ocudu_netconf/default_config.xml}:/config/default_config.xml
    networks:
      smo:
        ipv4_address: 172.21.0.14

  o1_adapter:
    image: ocudu/o1_adapter:latest
    build:
      context: ocudu_elements/ocudu_o1_adapter
      dockerfile: Dockerfile
    container_name: ocudu-o1_adapter
    ports:
      - 5000:5000
    tty: true
    command: python3 ./src/o1_adapter.py --netconf_host 172.21.0.14 --ws_host mock_gnb --ws_port 8001
    healthcheck:
      test: python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:5000/status')"
      interval: 10s
      timeout: 1s
      retries: 60
    depends_on:
      netconf:
        condition: service_started
      mock_gnb:
        condition: service_started
    environment:
      WS_HOST: ${O1_ADAPTER_WS_HOST:-mock_gnb}
      WS_PORT: ${O1_ADAPTER_WS_PORT:-8001}
      O1_ADAPTER_LOGLEVEL: DEBUG
    volumes:
      # Save generated config file to /tmp/config.yml and make it available to the test container
      - shared-data:/tmp
    networks:
      smo:
        ipv4_address: 172.21.0.13

  mock_gnb:
    image: ocudu/mock-gnb:latest
    build:
      context: ./mocks/mock_gnb
      dockerfile: Dockerfile
    container_name: ocudu-mock-gnb
    #ports:
      # Comment to hide the WS port from outside of the docker network
      #- 8001:8001
    environment:
      #MOCK_GNB_HOST: "172.21.0.16"
      MOCK_GNB_PORT: "8001"
      MOCK_GNB_EVENT_LOG: /tmp/mock_gnb_events.jsonl
      MOCK_GNB_LOGLEVEL: INFO
    networks:
      smo:
        ipv4_address: 172.21.0.16
    profiles: ["test"]
    volumes:
      - shared-data:/tmp
    restart: always
    healthcheck:
      test: python -c "import urllib.request; urllib.request.urlopen('http://172.21.0.13:5000/config-healthy')"
      interval: 10s
      timeout: 1s
      retries: 1      

  o1_tests:
    image: ocudu/o1_tests:latest
    build:
      context: tests
      dockerfile: Dockerfile
    container_name: ocudu-o1_tests
    depends_on:
      netconf:
        condition: service_started
      mock_gnb:
        condition: service_started
      o1_adapter:
        condition: service_healthy
    environment:
      NETCONF_HOST: ocudu-netconf
      NETCONF_PORT: "830"
      NETCONF_USERNAME: root
      NETCONF_PASSWORD: root
      O1_ADAPTER_HOST: ocudu-o1_adapter
      O1_ADAPTER_PORT: "5000"
      CONFIG_PATH: /tmp/config.yaml
      MOCK_GNB_EVENT_LOG: /tmp/mock_gnb_events.jsonl
    volumes:
      - shared-data:/tmp
    networks:
      smo:
        ipv4_address: 172.21.0.15
    profiles: ["test"]

volumes:
  shared-data:

networks:
  smo:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
